# Generated by Django 5.0.4 on 2024-10-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classroom',
            new_name='classrooms',
        ),
    ]
