# Generated by Django 5.0.4 on 2024-10-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_add_school_to_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['grade', 'room']},
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('grade', 'room', 'school'), name='unique_classroom'),
        ),
    ]
