# Generated by Django 5.0.4 on 2024-10-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_add_classroom_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='alias',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
